dataset:
  name: celeba
  data_root: data/celeba/img_align_celeba
  image_size: 64
  channels: 3
  recon_loss: mse
  download: false

dataloader:
  batch_size: 128
  num_workers: 4
  include_labels: false