dataset:
  name: dsprites
  npz_path: data/dsprites/dsprites_200k.npz
  url: "https://github.com/google-deepmind/dsprites-dataset/raw/master/dsprites_ndarray_co1sh3sc6or40x32y32_64x64.npz"
  image_size: 64
  channels: 1
  recon_loss: bce
  n_classes: 3
  val_fraction: 0.1
  test_fraction: 0.1

dataloader:
  batch_size: 256
  num_workers: 0
  include_labels: false